schema:
  - https://graphql.datocms.com:
      headers:
        Authorization: 97462e8700e8f03982f00c2f083f81
        X-Exclude-Invalid: true
documents: "./graphql/**/*.graphql"
generates:
  graphql/generated.ts:
    plugins:
      - typescript
      - typescript-operations:
          strictScalars: true
          scalars:
            BooleanType: boolean
            CustomData: Record<string, unknown>
            Date: string
            DateTime: string
            FloatType: number
            IntType: number
            ItemId: string
            JsonField: unknown
            MetaTagAttributes: Record<string, string>
            UploadId: string
      - typed-document-node
